# Generated by Django 4.2.3 on 2023-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savefile',
            name='campaign_data',
        ),
        migrations.AddField(
            model_name='savefile',
            name='flags',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='current_location',
            field=models.IntegerField(null=True),
        ),
    ]
