# Generated by Django 4.2.3 on 2023-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_files', '0002_remove_savefile_campaign_data_savefile_flags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='current_location',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='flags',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
